### PR TITLE
add 3 recent documets to new repo.

### PR DESCRIPTION
**Pull request by RobAltena**
These 3 documents were recently added to the documents but did not make the migration to deeplearning4j-docs.

### CODE REVIEW

**Comment by saudet** [comment]
These don't use the document generator from the main repo?

**Comment by RobAltena** [comment]
I don't know. The docs seem to have been in the main repo for a while. Never seen them picked up to the site.

**Comment by saudet** [comment]
Ah, they are. Yes, this step is rather manual until we figure out something with the CI server...

**Comment by saudet** [comment]
Oops, this has broken master though:
```
The page build failed for the `master` branch with the following error:

The variable `{{1.0,2.0,3.0}` on line 77 in `docs/_latest/nd4j-quickstart.md` was not properly closed with `}}`. For more information, see https://help.github.com/en/articles/page-build-failed-tag-not-properly-terminated.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.
```

**Comment by RobAltena** [comment]
I don't even know where to look to fix that. The new file:
https://github.com/eclipse/deeplearning4j-docs/blob/master/docs/_latest/nd4j-quickstart.md
renders fine. All the opening and closing curly braces match.

**Comment by crockpotveggies** [comment]
What's happening is the `{{}}` is being treated similarly to a moustache template, this is because we added {{autogenerated}} to the docs so that Java code could be automatically added where desired. What probably needs to happen is the autogen Python file be updated to handle this edge case.

**Pull request merged**
